version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_PROMETHEUS_BIND_IP: 172.19.0.3
      CONCOURSE_PROMETHEUS_BIND_PORT: 8081

  pushgateway:
    image: prom/pushgateway
    privileged: true
    depends_on: [concourse]
    ports:
      - "9091:9091"
      
  prometheus:
    build: prometheus/.
    privileged: true
    depends_on: [pushgateway]
    ports:
      - "9090:9090"

  # statsd:
  #   image: statsd/statsd
  #   ports:
  #     - "8125:8125"